# Generated by Django 3.2.7 on 2022-01-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('publish_date', models.DateField()),
                ('author', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
